// ─────────────────────────────────────────────
// BANDS IN BEND — Weekly Show Data
// Update this file each week to refresh the site
// ─────────────────────────────────────────────

const WEEK = {
  label: "August 24 – 30",
  year: "2026",
};

const SHOWS = [
  {
    day: "Monday",
    date: "August 24",
    shows: [
      { artist: "Austin B. Sweeney", venue: "On Tap", time: "6pm" },
      { artist: "Bluegrass Collective", venue: "Silver Moon Brewing", time: "6pm" },
      { artist: "Joyful Lane", venue: "River Run Taphouse", time: "5pm" },
      { artist: "Musicians Open Showcase", venue: "The Commonwealth Pub", time: "5pm" },
      { artist: "Toast - The Beast of Bread", venue: "Tower Theatre", time: "7pm" },
      { artist: "Weekly Live Music", venue: "Bend Brewing Company", time: "6pm" },
    ],
  },
  {
    day: "Tuesday",
    date: "August 25",
    shows: [
      { artist: "Chewtoy", venue: "The Commonwealth Pub", time: "7pm" },
      { artist: "Eric Leadbetter", venue: "Goodlife Brewing Company", time: "6pm" },
      { artist: "The Hip Abduction & Coyote Island", venue: "Midtown Ballroom", time: "7pm" },
      { artist: "Lave Butte Boys", venue: "Deschutes Brewery Beer Garden", time: "5pm" },
      { artist: "Nether Hour & Guests", venue: "Silver Moon Brewing", time: "6pm" },
      { artist: "Open Mic w/ Mari", venue: "The Cellar", time: "6pm" },
      { artist: "The Strokes w/ The Garden & ÖLÜM", venue: "Hayden Homes Amphitheater", time: "6pm" },
      { artist: "Weekly Live Music", venue: "Greg's Grill", time: "6pm" },
    ],
  },
  {
    day: "Wednesday",
    date: "August 26",
    shows: [
      { artist: "2 For Jazz", venue: "Austin Kitchen Wine Bar & Mercantile", time: "5pm" },
      { artist: "Acoustic Open Mic w/ Derek Michael Marc", venue: "Northside Bar & Grill", time: "6pm" },
      { artist: "Bigfoot County", venue: "Father Luke's Room", time: "7pm" },
      { artist: "The Black Heart Procession", venue: "The Domino Room", time: "7pm" },
      { artist: "Black Joe Lewis & The Honeybears", venue: "Volcanic Theatre Pub", time: "7pm" },
      { artist: "Eric Leadbetter", venue: "Crosscut Warming Hut No. 5", time: "6pm" },
      { artist: "Joyful Lane", venue: "Century Commons Taps & Trucks", time: "6pm" },
      { artist: "Pete Kartsounes", venue: "The Commonwealth Pub", time: "7:30pm" },
      { artist: "Steelhead & Guests performing JGB", venue: "Silver Moon Brewing", time: "6pm" },
    ],
  },
  {
    day: "Thursday",
    date: "August 27",
    shows: [
      { artist: "Big Treble", venue: "Stoller Wine Bar", time: "6pm" },
      { artist: "Brad Parsons", venue: "Deschutes Brewery Beer Garden", time: "4pm" },
      { artist: "Desert Howlers", venue: "Rivers Place Taphouse", time: "6pm" },
      { artist: "Doc Monos", venue: "Austin Kitchen Wine Bar & Mercantile", time: "5pm" },
      { artist: "Dry Canyon Stampede", venue: "The Coyote", time: "6pm" },
      { artist: "Eric Leadbetter", venue: "Bevel Craft Brewing", time: "6pm" },
      { artist: "Irish Traditional Music", venue: "The Cellar", time: "6pm" },
      { artist: "Jazz Jam hosted by Elise Franklin", venue: "The Commonwealth Pub", time: "7:30pm" },
      { artist: "Spacely Sprocket", venue: "Mountain Burger", time: "6pm" },
      { artist: "Travis Ehrenstrom Acoustic Trio", venue: "The Way West", time: "6:30pm" },
      { artist: "Victor Johnson", venue: "The Grove Market Hall", time: "6pm" },
      { artist: "Vinyl Night", venue: "Dogwood at The Pine Shed", time: "7pm" },
      { artist: "Will Grove", venue: "The Lot", time: "6pm" },
    ],
  },
  {
    day: "Friday",
    date: "August 28",
    shows: [
      { artist: "Baz Moto", venue: "The Commonwealth Pub", time: "8pm" },
      { artist: "Bill Powers Old Growth", venue: "Boneyard Pub", time: "6pm" },
      { artist: "Dave LiaBraaten", venue: "Currents at Riverhouse Lodge", time: "7pm" },
      { artist: "DJ Chuck Boogie & Xtina", venue: "General Duffy's Waterhole", time: "9pm" },
      { artist: "DJ Timothy Bee", venue: "Dogwood at The Pine Shed", time: "9pm" },
      { artist: "DJ WHIPLSH", venue: "The Coyote", time: "9pm" },
      { artist: "Eric Leadbetter", venue: "Portello Lounge", time: "6:30pm" },
      { artist: "Jared McComas", venue: "The Cellar", time: "6pm" },
      { artist: "The Session", venue: "Blacksmith Public House", time: "6:30pm" },
      { artist: "Star Monster", venue: "Volcanic Theatre Pub", time: "8pm" },
      { artist: "Thomas T And The Blue Chips", venue: "Worthy Brewing", time: "7pm" },
      { artist: "Train w/ Barenaked Ladies & Matt Nathanson", venue: "Hayden Homes Amphitheater", time: "5:45pm" },
      { artist: "Watkins Glen's Soulshine daydream", venue: "Silver Moon Brewing", time: "7pm" },
    ],
  },
  {
    day: "Saturday",
    date: "August 29",
    shows: [
      { artist: "3rd Annual Battle Of The Bands", venue: "Craft Kitchen & Brewery", time: "2-6pm" },
      { artist: "Alicia Rome", venue: "Stoller Wine Bar", time: "5pm" },
      { artist: "Bigfoot County", venue: "Schilling's Garden Market", time: "6:30pm" },
      { artist: "Broken Top Duo", venue: "Austin Kitchen Wine Bar & Mercantile", time: "5pm" },
      { artist: "Call Down Thunder", venue: "Volcanic Theatre Pub", time: "10:30pm" },
      { artist: "David Von Schlegell", venue: "The Cellar", time: "6pm" },
      { artist: "DJ WHIPLSH", venue: "The Coyote", time: "10pm" },
      { artist: "DJ's Lord Queen Cole, Statik.Myke, & Hypernight", venue: "The Capitol", time: "9pm" },
      { artist: "Holus Bolus", venue: "On Tap", time: "6pm" },
      { artist: "The Huckle Bearers", venue: "Runaround Sue Barbecue", time: "6pm" },
      { artist: "Jack Krouscup 5 (Saturday Jazz Sessions)", venue: "Rivers Place Taphouse", time: "6pm" },
      { artist: "Joyful Lane", venue: "Feast Food Company", time: "6pm" },
      { artist: "Logan & Sydney // Silvertone Devils", venue: "The Bite", time: "1pm & 6pm" },
      { artist: "Maria", venue: "Century Commons Taps & Trucks", time: "6pm" },
      { artist: "Mougli & Blues w/ Shovelbelt & Kill Line", venue: "M&J Tavern", time: "9pm" },
      { artist: "Mt. Joy", venue: "Hayden Homes Amphitheater", time: "7:30pm" },
      { artist: "Niko Moon", venue: "General Duffy's Waterhole", time: "5pm" },
      { artist: "Not Your Ex Lover (21+)", venue: "The Commonwealth Pub", time: "8pm" },
      { artist: "Paper Flowers: Remembering Fleetwood Mac", venue: "Silver Moon Brewing", time: "7pm" },
      { artist: "Piña Colada", venue: "Portello Lounge", time: "7pm" },
      { artist: "Schaab & Sofie", venue: "Dogwood at The Pine Shed", time: "9pm" },
      { artist: "Skillethead", venue: "Worthy Brewing", time: "7pm" },
      { artist: "Slow Goat, Spina, & Elk Twitch", venue: "Volcanic Theatre Pub", time: "8pm" },
      { artist: "So Much Closer", venue: "The Grove Market Hall", time: "6pm" },
      { artist: "Soul'd Out & The Cutman", venue: "Blacksmith Public House", time: "6:30pm" },
      { artist: "Switchback", venue: "Northside Bar & Grill", time: "8pm" },
    ],
  },
  {
    day: "Sunday",
    date: "August 30",
    shows: [
      { artist: "76th Street", venue: "Volcanic Theatre Pub", time: "7pm" },
      { artist: "Brandon Campbell Trio", venue: "10 Barrel West Side Pub", time: "5pm" },
      { artist: "Cover Story", venue: "Ballers & Brews", time: "4pm" },
      { artist: "Horse Feathers & Annika Hankshaw", venue: "Silver Moon Brewing", time: "6pm" },
      { artist: "Jason Aricella", venue: "Goodlife Brewing Company", time: "4pm" },
      { artist: "Leftslide", venue: "Boneyard Pub", time: "4pm" },
      { artist: "Long Gone Wilder", venue: "Trailhead Lodge", time: "5pm" },
      { artist: "Milo Matthews", venue: "Deschutes Brewery Beer Garden", time: "4pm" },
      { artist: "Piña Colada", venue: "Midtown Yacht Club", time: "6pm" },
      { artist: "Reb Conner", venue: "Currents at Riverhouse Lodge", time: "11am" },
      { artist: "Rogue City Renegades", venue: "Rivers Place Taphouse", time: "6pm" },
      { artist: "Shineola Singalong", venue: "The Commonwealth Pub", time: "4pm" },
    ],
  },
];

// Highlights shown on the cover — update each week
const HIGHLIGHTS = [
  { artist: "The Strokes", day: "Tue Aug 25" },
  { artist: "Black Joe Lewis", day: "Wed Aug 26" },
  { artist: "Star Monster", day: "Fri Aug 28" },
  { artist: "Battle of the Bands", day: "Sat Aug 29" },
  { artist: "Mt. Joy", day: "Sat Aug 29" },
];
